- name: Configure Splunk Cluster
  hosts: cluster_manager
  become: yes
  tasks:
    - name: Configure Cluster Manager
      become_user: splunk
      expect:
        command: /opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 3 -search_factor 2 -secret cluster -cluster_label cluster1
        responses:
          "Splunk username:": "admin"
          "Password:": "admin123"

    - name: Restart Splunk on Cluster Manager
      become_user: splunk
      command: /opt/splunk/bin/splunk restart

- name: Configure Indexer Nodes
  hosts: indexers
  become: yes
  tasks:
    - name: Configure Indexers as Peer Nodes
      become_user: splunk
      expect:
        command: /opt/splunk/bin/splunk edit cluster-config -mode peer -manager_uri https://18.212.199.35:8089 -replication_port 9887 -secret cluster
        responses:
          "Splunk username:": "admin"
          "Password:": "admin123"

    - name: Restart Splunk on Indexers
      become_user: splunk
      command: /opt/splunk/bin/splunk restart
