- hosts: ClusterManager
  tasks:
     - name: Configuring Manager Node
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret SoftManiaKey -cluster_label Indexer_Cluster -auth admin:admin123
          
     - name: splunk restart for Configuring Manager Node
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart
           
- hosts: indexers
  tasks:
     - name: Configuring Peer Nodes
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode peer -manager_uri https://{{ ClusterManager.ansible_host}}:8089 -replication_port 9887 -secret SoftManiaKey -auth admin:admin123
          
     - name: splunk restart for Configuring Manager Node
       become: yes
       become_user: root
       command:
            cmd: /opt/splunk/bin/splunk restart


- hosts: Deployer
  tasks:
    - name: enable the clustering in deployer
      become: yes
      become_user: splunk
      copy: 
         dest: /opt/splunk/etc/system/local/server.conf
         content: |
            [shclustering]
            pass4SymmKey = SoftManiaSHClusterKey
            shcluster_label = shcluster1
    - name: restart
      become: yes
      become_user: root
      command:
            cmd: /opt/splunk/bin/splunk restart
 
- name: search Head 1
  hosts: SH1
  user: root
  become: yes

  tasks:
      
    - name: configure search peer 
      command: /opt/splunk/bin/splunk init shcluster-config -auth admin:admin123 -mgmt_uri https://{{ search_heads.SH1.ansible_host }}:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://{{ Deployer.ansible_host }}:8089 -secret SoftManiaSHClusterKey -shcluster_label shcluster1

    - name: restart splunk
      command: /opt/splunk/bin/splunk restart

- name: search Head 2
  hosts: SH2
  user: root
  become: yes

  tasks:
      
    - name: configure search peer 
      command: /opt/splunk/bin/splunk init shcluster-config -auth admin:admin123 -mgmt_uri https://{{ search_heads.SH2.ansible_host }}:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://{{ Deployer.ansible_host }}:8089 -secret SoftManiaSHClusterKey -shcluster_label shcluster1

    - name: restart splunk
      command: /opt/splunk/bin/splunk restart

- name: search Head 3
  hosts: SH3
  user: root
  become: yes

  tasks:
      
    - name: configure search peer 
      command: /opt/splunk/bin/splunk init shcluster-config -auth admin:admin123 -mgmt_uri https://{{ search_heads.SH3.ansible_host }}:8089 -replication_port 9000 -replication_factor 3 -conf_deploy_fetch_url http://{{ Deployer.ansible_host }}:8089 -secret SoftManiaSHClusterKey -shcluster_label shcluster1

    - name: restart splunk
      command: /opt/splunk/bin/splunk restart


- name: shc 1 captain
  hosts: SH1
  user: root
  become: yes

  tasks:
    - name: Making cluster captain
      command: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "https://{{ search_heads.SH1.ansible_host }}:8089,https://{{ search_heads.SH2.ansible_host }}:8089,https://{{ search_heads.SH3.ansible_host }}:8089" -auth admin:admin123

- hosts: IFs
  tasks:
    - name: Configure Intermediate Forwarders
      command: /opt/splunk/bin/splunk set deploy-poll {{ Deployment-Server.ansible_host }}:8089
    
    - name: restart splunk
      command: /opt/splunk/bin/splunk restart


- name: Connect Search Head Cluster with Indexer Cluster
  hosts: search_heads
  become_user: root
  become: yes

  tasks:
    - name: configure indexer cluster with search head 
      command : /opt/splunk/bin/splunk edit cluster-config -mode searchhead -manager_uri https://{{ ClusterManager.ansible_host }}:8089 -secret SoftManiaKey -auth admin:admin123

    - name: restart splunk
      command: /opt/splunk/bin/splunk restart

